"use client";

import Link from "next/link";
import { useState } from "react";
import { SearchBar } from "@/components/search-bar";
import { PropertyCard } from "@/components/property-card";
import { Reveal } from "@/components/reveal";
import { useLanguage } from "@/components/providers";
import { cities, stays } from "@/lib/properties";

export default function HomePage() {
  const { pick } = useLanguage();
  const [prompt, setPrompt] = useState("");
  const [aiAnswer, setAiAnswer] = useState<string | null>(null);
  const askAi = async () => {
    if (!prompt.trim()) return;
    setAiAnswer(pick("Thinking across 46 verified stays…", "أبحث الآن بين 46 إقامة موثقة…"));
    try { const response = await fetch("/api/ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: prompt }) }); const data = await response.json() as { answer?: string }; setAiAnswer(data.answer ?? pick("Palm Court Resort in Jericho is your strongest match.", "منتجع ساحة النخيل في أريحا هو أفضل تطابق لك.")); }
    catch { setAiAnswer(pick("Gerizim View Chalet is a strong match for your trip.", "شاليه إطلالة جرزيم مناسب جدًا لرحلتك.")); }
  };

  return <>
    <section className="home-hero">
      <div className="hero-noise" /><div className="hero-glow" />
      <div className="hero-copy"><div className="overline"><i />{pick("The intelligent way to stay in Palestine", "الطريقة الأذكى للإقامة في فلسطين")}</div><h1>{pick("Stay local.", "أقم محليًا.")}<br /><em>{pick("Feel everywhere.", "واشعر بكل مكان.")}</em></h1><p>{pick("One trusted place to discover hotels, private chalets, villas and meaningful local stays — matched to you by AI.", "مكان موثوق واحد لاكتشاف الفنادق والشاليهات والفلل والإقامات المحلية التي يختارها الذكاء لتناسبك.")}</p><div className="hero-actions"><Link className="button button-mint" href="/explore">{pick("Explore Palestinian stays", "استكشف الإقامات الفلسطينية")} <span>↗</span></Link><Link className="play-link" href="/about"><i>▶</i>{pick("See how it works", "شاهد كيف نعمل")}</Link></div><div className="hero-trust"><div className="avatar-stack"><span>M</span><span>Y</span><span>L</span><span>+8k</span></div><div><b>4.9 <i>★★★★★</i></b><small>{pick("from verified local guests", "من ضيوف محليين موثقين")}</small></div></div></div>
      <div className="hero-gallery"><div className="hero-photo hero-photo-main" /><div className="hero-photo hero-photo-top" /><div className="hero-photo hero-photo-bottom" /><div className="floating-proof"><span>✦</span><div><b>{pick("98% match", "تطابق 98%")}</b><small>{pick("for your weekend", "لعطلة نهاية أسبوعك")}</small></div></div><div className="floating-price"><small>{pick("Tonight in Jericho", "الليلة في أريحا")}</small><b>$84 <span>{pick("avg.", "متوسط")}</span></b><i>↓ 12%</i></div></div>
      <div className="hero-search"><SearchBar /></div>
    </section>

    <div className="motion-strip"><div>{Array.from({ length: 2 }).map((_, group) => <span key={group}>PALESTINIAN STAYS <i>✦</i> TRUSTED HOSTS <i>✦</i> SMARTER TRAVEL <i>✦</i> FAIRER PRICES <i>✦</i> LOCAL STORIES <i>✦</i></span>)}</div></div>

    <section className="content-section featured-section"><Reveal><div className="section-head"><div><span className="kicker">{pick("CURATED FOR YOU", "مختارة لك")}</span><h2>{pick("Places with a point of view.", "أماكن لها قصتها الخاصة.")}</h2><p>{pick("Independent stays, warm hosts and the corners guests remember.", "إقامات مستقلة ومضيفون رائعون وتفاصيل لا تُنسى.")}</p></div><Link href="/explore">{pick("View all stays", "عرض كل الإقامات")} <span>↗</span></Link></div></Reveal><div className="stays-grid">{stays.slice(0, 6).map((stay, index) => <Reveal key={stay.id} delay={index * 70}><PropertyCard stay={stay} priority={index < 3} /></Reveal>)}</div></section>

    <section className="ai-concierge-section"><div className="ai-orbit orbit-one" /><div className="ai-orbit orbit-two" /><div className="content-section ai-concierge-grid"><Reveal className="ai-copy"><span className="kicker kicker-light">SMARTSTAY CONCIERGE</span><h2>{pick("Tell us the feeling.", "أخبرنا بالشعور.")}<br /><em>{pick("We’ll find the place.", "وسنجد لك المكان.")}</em></h2><p>{pick("No filter maze. Describe who is travelling, your budget and what would make the trip feel right.", "لا مزيد من الفلاتر المعقدة. صف المسافرين والميزانية وما الذي يجعل الرحلة مثالية.")}</p><div className="ai-points"><span><i>01</i>{pick("Understands natural language", "يفهم لغتك الطبيعية")}</span><span><i>02</i>{pick("Reads hundreds of reviews", "يقرأ مئات التقييمات")}</span><span><i>03</i>{pick("Explains every recommendation", "يشرح سبب كل توصية")}</span></div></Reveal><Reveal className="ai-console" delay={140}><div className="console-top"><div><span className="ai-mark">✦</span><p><b>StaySense AI</b><small><i /> {pick("Free local intelligence", "ذكاء محلي مجاني")}</small></p></div><span>•••</span></div><div className="ai-message">{pick("Describe the trip you have in mind. Details make my matches better.", "صف الرحلة التي تفكر بها. كل تفصيل يساعدني على اختيار أفضل.")}</div><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder={pick("A private chalet near Nablus for 8 people, heated pool, mountain view, Friday to Saturday…", "شاليه خاص قرب نابلس لـ8 أشخاص، مسبح مدفأ وإطلالة جبلية، من الجمعة للسبت…")} /><div className="prompt-chips"><button onClick={() => setPrompt(pick("Family stay with a private pool in Jericho", "إقامة عائلية مع مسبح خاص في أريحا"))}>☀ {pick("Family escape", "عطلة عائلية")}</button><button onClick={() => setPrompt(pick("Romantic stone villa near Bethlehem", "فيلا حجرية رومانسية قرب بيت لحم"))}>♡ {pick("Couples", "للأزواج")}</button><button onClick={() => setPrompt(pick("Affordable city hotel in Ramallah", "فندق بسعر مناسب في رام الله"))}>$ {pick("Best value", "أفضل سعر")}</button></div><button className="ai-action" onClick={askAi}>✦ {pick("Build my shortlist", "أنشئ قائمتي")} <span>→</span></button>{aiAnswer && <div className="ai-response"><span>✦</span><p>{aiAnswer}</p><Link href="/explore">{pick("See matches", "عرض النتائج")} →</Link></div>}</Reveal></div></section>

    <section className="content-section city-section"><Reveal><div className="section-head"><div><span className="kicker">{pick("GO SOMEWHERE REAL", "اذهب لمكان حقيقي")}</span><h2>{pick("Five cities. Endless stories.", "خمس مدن. حكايات لا تنتهي.")}</h2></div></div></Reveal><div className="city-grid">{cities.map((city, index) => <Reveal key={city.en} delay={index * 80}><Link href={`/explore?city=${city.en}`} className="city-card" style={{ backgroundImage: `linear-gradient(180deg, transparent 35%, rgba(7,19,25,.86)),url(${city.image})` }}><span>0{index + 1}</span><div><h3>{pick(city.en, city.ar)}</h3><p>{city.count} {pick("verified stays", "إقامة موثقة")}</p></div><i>↗</i></Link></Reveal>)}</div></section>

    <section className="host-story"><div className="host-image"><div className="host-earn"><small>{pick("This month", "هذا الشهر")}</small><b>$3,840</b><span>↗ 18.6%</span></div></div><Reveal className="host-copy"><span className="kicker">{pick("BUILT FOR LOCAL HOSTS", "مصمم للمضيف الفلسطيني")}</span><h2>{pick("Your place deserves", "مكانك يستحق")}<br /><em>{pick("more than a listing.", "أكثر من مجرد إعلان.")}</em></h2><p>{pick("Smart pricing, protected bookings, guest verification and performance insight — everything a serious host needs to grow.", "تسعير ذكي وحجوزات محمية وتحقق من الضيوف وتقارير أداء — كل ما يحتاجه المالك لينمو.")}</p><ul><li><span>✓</span>{pick("Add unlimited properties and photo galleries", "أضف منشآت وصورًا بلا حدود")}</li><li><span>✓</span>{pick("Real-time availability prevents double bookings", "توفر لحظي يمنع الحجز المزدوج")}</li><li><span>✓</span>{pick("Occupancy, revenue and AI performance reports", "تقارير إشغال وأرباح وتوصيات ذكية")}</li></ul><Link className="button button-dark" href="/host">{pick("Start hosting", "ابدأ الاستضافة")} <span>↗</span></Link><Link className="host-login" href="/login">{pick("Already a host? Sign in", "أنت مضيف بالفعل؟ سجل الدخول")}</Link></Reveal></section>

    <section className="content-section steps-section"><Reveal><div className="section-head centered"><div><span className="kicker">{pick("BOOK WITH CERTAINTY", "احجز بثقة")}</span><h2>{pick("From idea to check-in.", "من الفكرة إلى تسجيل الوصول.")}</h2></div></div></Reveal><div className="steps-grid">{[["01","Search your way","Use dates and filters, or simply tell AI what the trip should feel like.","ابحث بطريقتك","استخدم التواريخ والفلاتر أو أخبر الذكاء بما تريده."],["02","Know before you go","Verified details, review intelligence and transparent total pricing.","اعرف قبل أن تذهب","بيانات موثقة وتحليل مراجعات وسعر نهائي شفاف."],["03","Book without overlap","Your exact date and time are locked instantly and cannot be sold twice.","احجز دون تعارض","يُقفل تاريخك ووقتك فورًا ولا يمكن بيعه مرة أخرى."]].map(([number,title,text,titleAr,textAr], index) => <Reveal key={number} delay={index*90}><div className="step-card"><span>{number}</span><i>{["⌕","✦","✓"][index]}</i><h3>{pick(title,titleAr)}</h3><p>{pick(text,textAr)}</p></div></Reveal>)}</div></section>

    <section className="final-cta"><div className="cta-glow" /><span className="kicker kicker-light">{pick("YOUR NEXT STORY IS LOCAL", "قصتك القادمة محلية")}</span><h2>{pick("Find a stay worth remembering.", "ابحث عن إقامة تستحق أن تتذكرها.")}</h2><p>{pick("Verified Palestinian places. Fair prices. Smarter decisions.", "أماكن فلسطينية موثقة. أسعار عادلة. قرارات أذكى.")}</p><div><Link className="button button-mint" href="/explore">{pick("Explore stays", "استكشف الإقامات")} ↗</Link><Link className="button button-ghost-light" href="/host">{pick("List your property", "أضف منشأتك")}</Link></div></section>
  </>;
}
