"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useLanguage } from "./providers";
import type { UserRole } from "@/lib/types";

export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const { pick } = useLanguage();
  const [name,setName] = useState(""); const [email,setEmail] = useState(""); const [phone,setPhone] = useState(""); const [password,setPassword] = useState("");
  const [role,setRole] = useState<UserRole>("customer"); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); const response = await fetch(`/api/auth/${mode}`, { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify(mode === "login" ? {email,password} : {name,email,phone,password,role}) }); const data = await response.json() as {error?:string;user?:{role:UserRole}}; if(!response.ok){setError(data.error||pick("Something went wrong.","حدث خطأ ما."));setLoading(false);return;} const userRole=data.user?.role||role; window.location.href=userRole==="owner"?"/owner":userRole==="admin"?"/admin":"/dashboard"; };
  const demo = (kind: "guest"|"owner"|"admin") => { setEmail(`${kind}@smartstay.ps`); setPassword(`${kind.charAt(0).toUpperCase()+kind.slice(1)}123!`); };
  return <div className="auth-card"><div className="auth-card-head"><span className="kicker">{mode === "login" ? pick("WELCOME BACK", "مرحبًا بعودتك") : pick("JOIN SMARTSTAY", "انضم إلى SMARTSTAY")}</span><h1>{mode === "login" ? pick("Sign in to continue.", "سجل الدخول للمتابعة.") : pick("Create your account.", "أنشئ حسابك.")}</h1><p>{mode === "login" ? pick("Manage trips, bookings and properties from one secure account.", "أدر رحلاتك وحجوزاتك ومنشآتك من حساب آمن واحد.") : pick("Book local stays or grow your property business.", "احجز إقامات محلية أو نمِّ نشاط منشأتك.")}</p></div>{mode === "register" && <div className="role-choice"><button className={role === "customer" ? "active" : ""} onClick={()=>setRole("customer")}><span>♙</span><b>{pick("I'm a guest", "أنا ضيف")}</b><small>{pick("Discover and book stays", "اكتشف واحجز الإقامات")}</small></button><button className={role === "owner" ? "active" : ""} onClick={()=>setRole("owner")}><span>⌂</span><b>{pick("I'm a host", "أنا مضيف")}</b><small>{pick("List and manage properties", "أضف وأدر منشآتك")}</small></button></div>}<form onSubmit={submit}>{mode === "register" && <><label>{pick("Full name", "الاسم الكامل")}<input value={name} onChange={(event)=>setName(event.target.value)} placeholder="Maya Khalil" required /></label><label>{pick("Phone number", "رقم الهاتف")}<input value={phone} onChange={(event)=>setPhone(event.target.value)} placeholder="+970 59 000 0000" /></label></>}<label>{pick("Email address", "البريد الإلكتروني")}<input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="name@example.com" required /></label><label>{pick("Password", "كلمة المرور")}<input type="password" value={password} onChange={(event)=>setPassword(event.target.value)} placeholder="Minimum 8 characters" required /></label>{error && <div className="form-error">! {error}</div>}<button className="button button-mint auth-submit" disabled={loading}>{loading ? pick("Please wait…", "يرجى الانتظار…") : mode === "login" ? pick("Sign in securely", "تسجيل دخول آمن") : pick("Create my account", "إنشاء حسابي")} →</button></form>{mode === "login" && <div className="demo-login"><span>{pick("Demo accounts", "حسابات للتجربة")}</span><div><button onClick={()=>demo("guest")}>{pick("Guest", "ضيف")}</button><button onClick={()=>demo("owner")}>{pick("Owner", "مالك")}</button><button onClick={()=>demo("admin")}>{pick("Admin", "إدارة")}</button></div></div>}<p className="auth-switch">{mode === "login" ? pick("New to SmartStay?", "جديد على SmartStay؟") : pick("Already have an account?", "لديك حساب بالفعل؟")} <Link href={mode === "login" ? "/register" : "/login"}>{mode === "login" ? pick("Create an account", "أنشئ حسابًا") : pick("Sign in", "سجل الدخول")}</Link></p></div>;
}
