import type { Stay } from "./types";

const images = {
  jericho: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=88",
  bethlehem: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=88",
  ramallah: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1600&q=88",
  nablus: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=88",
  rawabi: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=88",
  hebron: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1600&q=88",
  farm: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1600&q=88",
  villa: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=1600&q=88",
  gaza: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1600&q=88",
};

const gallery = [
  "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=86",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=86",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=86",
];

export const stays: Stay[] = [
  { id: 101, slug: "palm-court-jericho", name: "Palm Court Resort", nameAr: "منتجع ساحة النخيل", type: "Resort", typeAr: "منتجع", city: "Jericho", cityAr: "أريحا", area: "Al-Maghtas Road", areaAr: "طريق المغطس", price: 165, rating: 4.92, reviews: 284, guests: 8, bedrooms: 4, bathrooms: 3, image: images.jericho, gallery, amenities: ["Private pool", "Family garden", "Breakfast", "Free parking"], amenitiesAr: ["مسبح خاص", "حديقة عائلية", "إفطار", "موقف مجاني"], description: "A private palm-lined retreat designed for long family afternoons, warm evenings and effortless access to Jericho's historic heart.", descriptionAr: "إقامة خاصة بين أشجار النخيل، مصممة للعائلات وقريبة من قلب أريحا التاريخي.", badge: "Guest favourite", badgeAr: "مفضل لدى الضيوف", instant: true, latitude: 31.8611, longitude: 35.4618 },
  { id: 102, slug: "stone-house-bethlehem", name: "The Stone House", nameAr: "البيت الحجري", type: "Villa", typeAr: "فيلا", city: "Bethlehem", cityAr: "بيت لحم", area: "Beit Jala Hills", areaAr: "تلال بيت جالا", price: 138, rating: 4.88, reviews: 146, guests: 6, bedrooms: 3, bathrooms: 2, image: images.bethlehem, gallery, amenities: ["Valley view", "Fireplace", "Chef kitchen", "Work space"], amenitiesAr: ["إطلالة الوادي", "مدفأة", "مطبخ مجهز", "مساحة عمل"], description: "Contemporary comfort inside timeless Palestinian stone, with calm terraces overlooking the hills of Beit Jala.", descriptionAr: "راحة عصرية داخل حجر فلسطيني أصيل مع تراسات هادئة تطل على تلال بيت جالا.", badge: "Design stay", badgeAr: "إقامة بتصميم مميز", instant: false, latitude: 31.7157, longitude: 35.1879 },
  { id: 103, slug: "manara-suites-ramallah", name: "Manara Urban Suites", nameAr: "أجنحة المنارة", type: "Hotel", typeAr: "فندق", city: "Ramallah", cityAr: "رام الله", area: "Al-Masyoun", areaAr: "الماصيون", price: 96, rating: 4.81, reviews: 519, guests: 3, bedrooms: 1, bathrooms: 1, image: images.ramallah, gallery, amenities: ["Rooftop lounge", "City view", "Gym", "24/7 reception"], amenitiesAr: ["تراس علوي", "إطلالة المدينة", "نادي رياضي", "استقبال 24/7"], description: "A polished city base with thoughtful service, productive spaces and Ramallah's dining scene minutes away.", descriptionAr: "قاعدة حضرية أنيقة مع خدمة مميزة ومساحات عمل ومطاعم رام الله على بعد دقائق.", badge: "Best city stay", badgeAr: "الأفضل داخل المدينة", instant: true, latitude: 31.9038, longitude: 35.2034 },
  { id: 104, slug: "gerizim-view-nablus", name: "Gerizim View Chalet", nameAr: "شاليه إطلالة جرزيم", type: "Chalet", typeAr: "شاليه", city: "Nablus", cityAr: "نابلس", area: "Mount Gerizim", areaAr: "جبل جرزيم", price: 122, rating: 4.94, reviews: 198, guests: 10, bedrooms: 4, bathrooms: 3, image: images.nablus, gallery, amenities: ["Heated pool", "Mountain view", "BBQ deck", "Kids zone"], amenitiesAr: ["مسبح مدفأ", "إطلالة جبلية", "جلسة شواء", "منطقة أطفال"], description: "A dramatic mountain chalet built for gatherings, with a heated pool and uninterrupted views across Nablus.", descriptionAr: "شاليه جبلي للتجمعات مع مسبح مدفأ وإطلالة بانورامية على نابلس.", badge: "AI top match", badgeAr: "أفضل تطابق بالذكاء", instant: true, latitude: 32.1986, longitude: 35.2722 },
  { id: 105, slug: "rawabi-skyline-loft", name: "Rawabi Skyline Loft", nameAr: "لوفت أفق روابي", type: "Apartment", typeAr: "شقة", city: "Rawabi", cityAr: "روابي", area: "Q Center", areaAr: "كيو سنتر", price: 84, rating: 4.76, reviews: 92, guests: 4, bedrooms: 2, bathrooms: 2, image: images.rawabi, gallery, amenities: ["Smart home", "Balcony", "Fast Wi-Fi", "Self check-in"], amenitiesAr: ["منزل ذكي", "شرفة", "إنترنت سريع", "دخول ذاتي"], description: "A bright, connected apartment for weekend escapes and productive stays in Palestine's newest urban centre.", descriptionAr: "شقة مشرقة ومتصلة مناسبة لعطلة نهاية الأسبوع والعمل في أحدث مركز حضري فلسطيني.", badge: "New this week", badgeAr: "جديد هذا الأسبوع", instant: true, latitude: 32.0125, longitude: 35.1847 },
  { id: 106, slug: "old-city-courtyard-hebron", name: "Old City Courtyard", nameAr: "دار البلدة القديمة", type: "Guesthouse", typeAr: "بيت ضيافة", city: "Hebron", cityAr: "الخليل", area: "Old City", areaAr: "البلدة القديمة", price: 74, rating: 4.87, reviews: 167, guests: 5, bedrooms: 2, bathrooms: 1, image: images.hebron, gallery, amenities: ["Heritage design", "Courtyard", "Local breakfast", "Walking tours"], amenitiesAr: ["تصميم تراثي", "باحة داخلية", "فطور بلدي", "جولات مشي"], description: "A restored heritage stay where carved stone, a quiet courtyard and local hospitality tell the story of Hebron.", descriptionAr: "إقامة تراثية مرممة تجمع الحجر المنحوت والباحة الهادئة والضيافة الخليلية.", badge: "Local experience", badgeAr: "تجربة محلية", instant: false, latitude: 31.5326, longitude: 35.0998 },
  { id: 107, slug: "olive-grove-tulkarm", name: "Olive Grove Farmstay", nameAr: "مزرعة بستان الزيتون", type: "Farmstay", typeAr: "مزرعة", city: "Tulkarm", cityAr: "طولكرم", area: "Iktaba", areaAr: "اكتابا", price: 88, rating: 4.9, reviews: 110, guests: 12, bedrooms: 5, bathrooms: 4, image: images.farm, gallery, amenities: ["Olive grove", "Outdoor kitchen", "Playground", "Event space"], amenitiesAr: ["بستان زيتون", "مطبخ خارجي", "ملعب أطفال", "مساحة مناسبات"], description: "A generous countryside stay for large families, celebrations and slow mornings among olive trees.", descriptionAr: "إقامة ريفية واسعة للعائلات الكبيرة والمناسبات وصباحات هادئة بين أشجار الزيتون.", badge: "Great for groups", badgeAr: "مثالية للمجموعات", instant: true, latitude: 32.3104, longitude: 35.0286 },
  { id: 108, slug: "jenin-hills-villa", name: "Jenin Hills Villa", nameAr: "فيلا تلال جنين", type: "Villa", typeAr: "فيلا", city: "Jenin", cityAr: "جنين", area: "Al-Jabriyat", areaAr: "الجابريات", price: 149, rating: 4.86, reviews: 73, guests: 9, bedrooms: 4, bathrooms: 3, image: images.villa, gallery, amenities: ["Infinity pool", "Sunset terrace", "BBQ", "Private entrance"], amenitiesAr: ["مسبح إنفينيتي", "تراس الغروب", "شواء", "مدخل خاص"], description: "A serene hillside villa with wide sunset views, generous living spaces and complete privacy.", descriptionAr: "فيلا هادئة على التلال مع إطلالة غروب واسعة ومساحات معيشة وخصوصية كاملة.", badge: "Sunset pick", badgeAr: "اختيار الغروب", instant: true, latitude: 32.4615, longitude: 35.2997 },
  { id: 109, slug: "gaza-seafront-house", name: "Gaza Seafront House", nameAr: "دار شاطئ غزة", type: "Villa", typeAr: "فيلا", city: "Gaza", cityAr: "غزة", area: "Al-Rimal", areaAr: "حي الرمال", price: 118, rating: 4.91, reviews: 132, guests: 7, bedrooms: 3, bathrooms: 2, image: images.gaza, gallery, amenities: ["Sea view", "Private terrace", "Family kitchen", "Fast Wi-Fi"], amenitiesAr: ["إطلالة بحرية", "تراس خاص", "مطبخ عائلي", "إنترنت سريع"], description: "A bright coastal home with a private terrace, generous family space and open views toward the Mediterranean.", descriptionAr: "بيت ساحلي مشرق مع تراس خاص ومساحة عائلية واسعة وإطلالة مفتوحة على البحر المتوسط.", badge: "Coastal favourite", badgeAr: "مفضل على الساحل", instant: true, latitude: 31.5017, longitude: 34.4668 },
];

export const cities = [
  { en: "Jericho", ar: "أريحا", count: 46, image: images.jericho },
  { en: "Bethlehem", ar: "بيت لحم", count: 32, image: images.bethlehem },
  { en: "Ramallah", ar: "رام الله", count: 71, image: images.ramallah },
  { en: "Nablus", ar: "نابلس", count: 39, image: images.nablus },
  { en: "Gaza", ar: "غزة", count: 28, image: images.gaza },
];

export function findStay(slug: string) {
  return stays.find((stay) => stay.slug === slug);
}
